"""Curated commercial retail listings from major brokerages — aligned with catchment/street data."""

from __future__ import annotations

COMMERCIAL_BROKERS = {
    "jll": {
        "name": "JLL",
        "full_name": "Jones Lang LaSalle",
        "website": "https://www.jll.co.uk",
        "listing_portal": "https://property.jll.com",
        "tier": "global",
    },
    "cbre": {
        "name": "CBRE",
        "full_name": "CBRE Group",
        "website": "https://www.cbre.com",
        "listing_portal": "https://www.cbre.com/properties",
        "tier": "global",
    },
    "cushman": {
        "name": "Cushman & Wakefield",
        "full_name": "Cushman & Wakefield",
        "website": "https://www.cushmanwakefield.com",
        "listing_portal": "https://www.cushmanwakefield.com/en/properties",
        "tier": "global",
    },
    "savills": {
        "name": "Savills",
        "full_name": "Savills plc",
        "website": "https://www.savills.com",
        "listing_portal": "https://search.savills.com",
        "tier": "global",
    },
    "knight_frank": {
        "name": "Knight Frank",
        "full_name": "Knight Frank LLP",
        "website": "https://www.knightfrank.com",
        "listing_portal": "https://www.knightfrank.com/properties",
        "tier": "global",
    },
    "colliers": {
        "name": "Colliers",
        "full_name": "Colliers International",
        "website": "https://www.colliers.com",
        "listing_portal": "https://www.colliers.com/en-gb/properties",
        "tier": "global",
    },
    "bnp": {
        "name": "BNP Paribas RE",
        "full_name": "BNP Paribas Real Estate",
        "website": "https://www.realestate.bnpparibas.com",
        "listing_portal": "https://www.realestate.bnpparibas.co.uk",
        "tier": "europe",
    },
    "catella": {
        "name": "Catella",
        "full_name": "Catella Property Group",
        "website": "https://www.catella.com",
        "listing_portal": "https://www.catella.com/en/Transactions",
        "tier": "europe",
    },
    "engel_volkers": {
        "name": "Engel & Völkers Commercial",
        "full_name": "Engel & Völkers",
        "website": "https://www.engelvoelkers.com",
        "listing_portal": "https://www.engelvoelkers.com/com",
        "tier": "europe",
    },
    "local": {
        "name": "Local Agent",
        "full_name": "Independent Commercial Agent",
        "website": "",
        "listing_portal": "",
        "tier": "local",
    },
}

# Hand-curated retail units on or near known MELLER catchment streets.
# Sources: public broker portals (JLL, CBRE, Savills, etc.) — representative listings.
CITY_COMMERCIAL_LISTINGS: dict[str, list[dict]] = {
    "Barcelona": [
        {
            "id": "bcn-jll-portaferrissa",
            "title": "Retail Unit — Gothic Quarter",
            "address": "Carrer de la Portaferrissa 22, 08002 Barcelona",
            "latitude": 41.3832, "longitude": 2.1748,
            "broker_id": "jll", "size_sqm": 95, "rent_eur_monthly": 8200,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "bcn-gothic", "street_name": "Carrer de la Portaferrissa",
            "description": "Ground-floor retail with 4.2m ceiling height. High tourist footfall.",
        },
        {
            "id": "bcn-cbre-born",
            "title": "Corner Retail — El Born",
            "address": "Carrer de l'Argenteria 55, 08003 Barcelona",
            "latitude": 41.3848, "longitude": 2.1835,
            "broker_id": "cbre", "size_sqm": 110, "rent_eur_monthly": 9500,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "bcn-born", "street_name": "Carrer de l'Argenteria",
            "description": "Corner unit near Picasso Museum. Strong lifestyle retail corridor.",
        },
        {
            "id": "bcn-savills-pg",
            "title": "Flagship Retail — Passeig de Gràcia",
            "address": "Passeig de Gràcia 85, 08008 Barcelona",
            "latitude": 41.3945, "longitude": 2.1615,
            "broker_id": "savills", "size_sqm": 180, "rent_eur_monthly": 22000,
            "property_type": "retail_high_street", "availability": "under_offer",
            "catchment_id": "bcn-passeig-gracia", "street_name": "Passeig de Gràcia",
            "description": "Premium boulevard frontage. Luxury fashion neighbours.",
        },
        {
            "id": "bcn-cushman-eixample",
            "title": "Retail Space — Eixample",
            "address": "Carrer de Provença 250, 08008 Barcelona",
            "latitude": 41.3920, "longitude": 2.1650,
            "broker_id": "cushman", "size_sqm": 75, "rent_eur_monthly": 6800,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "bcn-eixample", "street_name": "Carrer de Provença",
            "description": "Modern unit near Diagonal. Good public transport links.",
        },
        {
            "id": "bcn-kf-gracia",
            "title": "Boutique Retail — Gràcia",
            "address": "Carrer de Verdi 45, 08012 Barcelona",
            "latitude": 41.4035, "longitude": 2.1575,
            "broker_id": "knight_frank", "size_sqm": 65, "rent_eur_monthly": 4200,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "bcn-gracia", "street_name": "Carrer de Verdi",
            "description": "Creative district. Lower rent, strong local community.",
        },
    ],
    "Paris": [
        {
            "id": "par-jll-marais",
            "title": "Retail — Le Marais",
            "address": "17 Rue des Francs-Bourgeois, 75004 Paris",
            "latitude": 48.8575, "longitude": 2.3580,
            "broker_id": "jll", "size_sqm": 85, "rent_eur_monthly": 14500,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "par-marais", "street_name": "Rue des Rosiers",
            "description": "Fashion district. Near MELLER Paris store on Rue des Rosiers.",
        },
        {
            "id": "par-cbre-champs",
            "title": "Luxury Retail — Champs-Élysées",
            "address": "102 Avenue des Champs-Élysées, 75008 Paris",
            "latitude": 48.8720, "longitude": 2.3025,
            "broker_id": "cbre", "size_sqm": 200, "rent_eur_monthly": 45000,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "par-champs", "street_name": "Avenue des Champs-Élysées",
            "description": "Iconic boulevard. Premium eyewear corridor.",
        },
        {
            "id": "par-savills-saint-germain",
            "title": "Retail Unit — Saint-Germain",
            "address": "145 Boulevard Saint-Germain, 75006 Paris",
            "latitude": 48.8530, "longitude": 2.3340,
            "broker_id": "savills", "size_sqm": 70, "rent_eur_monthly": 11000,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "par-saint-germain", "street_name": "Boulevard Saint-Germain",
            "description": "Left Bank lifestyle retail. Strong tourist and local mix.",
        },
    ],
    "Amsterdam": [
        {
            "id": "ams-jll-kalverstraat",
            "title": "Prime Retail — Kalverstraat",
            "address": "Kalverstraat 152, 1012 XE Amsterdam",
            "latitude": 52.3698, "longitude": 4.8905,
            "broker_id": "jll", "size_sqm": 120, "rent_eur_monthly": 18000,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "ams-centrum", "street_name": "Kalverstraat",
            "description": "Netherlands' busiest shopping street. Near MELLER at 160 Kalverstraat.",
        },
        {
            "id": "ams-cbre-negen",
            "title": "Retail — De Negen Straatjes",
            "address": "Hartenstraat 14, 1016 CB Amsterdam",
            "latitude": 52.3705, "longitude": 4.8840,
            "broker_id": "cbre", "size_sqm": 55, "rent_eur_monthly": 7500,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "ams-negen", "street_name": "Hartenstraat",
            "description": "Nine Streets boutique district. High fashion density.",
        },
        {
            "id": "ams-colliers-jordaan",
            "title": "Corner Shop — Jordaan",
            "address": "Westermarkt 12, 1016 DJ Amsterdam",
            "latitude": 52.3745, "longitude": 4.8835,
            "broker_id": "colliers", "size_sqm": 80, "rent_eur_monthly": 9200,
            "property_type": "retail_high_street", "availability": "under_offer",
            "catchment_id": "ams-jordaan", "street_name": "Westermarkt",
            "description": "Canal-side retail. Strong weekend footfall.",
        },
    ],
    "London": [
        {
            "id": "lon-jll-carnaby",
            "title": "Retail — Carnaby Street",
            "address": "45 Carnaby Street, London W1F 9PS",
            "latitude": 51.5135, "longitude": -0.1385,
            "broker_id": "jll", "size_sqm": 90, "rent_eur_monthly": 28000,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "lon-soho", "street_name": "Carnaby Street",
            "description": "Soho fashion hub. Strong youth and tourist traffic.",
        },
        {
            "id": "lon-cbre-covent",
            "title": "Flagship Retail — Covent Garden",
            "address": "28 Long Acre, London WC2E 9JT",
            "latitude": 51.5125, "longitude": -0.1225,
            "broker_id": "cbre", "size_sqm": 150, "rent_eur_monthly": 35000,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "lon-covent", "street_name": "Long Acre",
            "description": "Premium West End location. High brand visibility.",
        },
        {
            "id": "lon-savills-shoreditch",
            "title": "Creative Retail — Shoreditch",
            "address": "15 Redchurch Street, London E2 7DJ",
            "latitude": 51.5240, "longitude": -0.0785,
            "broker_id": "savills", "size_sqm": 70, "rent_eur_monthly": 12000,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "lon-shoreditch", "street_name": "Redchurch Street",
            "description": "East London creative quarter. Design-forward audience.",
        },
    ],
    "Milan": [
        {
            "id": "mil-jll-quadrilatero",
            "title": "Luxury Retail — Quadrilatero",
            "address": "Via Montenapoleone 12, 20121 Milano",
            "latitude": 45.4685, "longitude": 9.1945,
            "broker_id": "jll", "size_sqm": 100, "rent_eur_monthly": 25000,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "mil-quadrilatero", "street_name": "Via Montenapoleone",
            "description": "Italy's luxury fashion district.",
        },
        {
            "id": "mil-cbre-brera",
            "title": "Boutique Retail — Brera",
            "address": "Via Fiori Chiari 8, 20121 Milano",
            "latitude": 45.4715, "longitude": 9.1875,
            "broker_id": "cbre", "size_sqm": 60, "rent_eur_monthly": 8500,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "mil-brera", "street_name": "Via Fiori Chiari",
            "description": "Art district with growing lifestyle retail.",
        },
    ],
    "Berlin": [
        {
            "id": "ber-jll-kurfurstendamm",
            "title": "Retail — Kurfürstendamm",
            "address": "Kurfürstendamm 195, 10707 Berlin",
            "latitude": 52.5025, "longitude": 13.3255,
            "broker_id": "jll", "size_sqm": 110, "rent_eur_monthly": 9500,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "ber-kudamm", "street_name": "Kurfürstendamm",
            "description": "Berlin's premier shopping boulevard.",
        },
        {
            "id": "ber-cbre-mitte",
            "title": "Retail Unit — Mitte",
            "address": "Rosenthaler Straße 40, 10178 Berlin",
            "latitude": 52.5245, "longitude": 13.4025,
            "broker_id": "cbre", "size_sqm": 85, "rent_eur_monthly": 7200,
            "property_type": "unit_shop", "availability": "available",
            "catchment_id": "ber-mitte", "street_name": "Rosenthaler Straße",
            "description": "Central Berlin creative retail corridor.",
        },
    ],
    "Madrid": [
        {
            "id": "mad-savills-serrano",
            "title": "Luxury Retail — Calle de Serrano",
            "address": "Calle de Serrano 45, 28001 Madrid",
            "latitude": 40.4285, "longitude": -3.6865,
            "broker_id": "savills", "size_sqm": 95, "rent_eur_monthly": 14000,
            "property_type": "retail_high_street", "availability": "available",
            "catchment_id": "mad-salamanca", "street_name": "Calle de Serrano",
            "description": "Salamanca luxury shopping district.",
        },
        {
            "id": "mad-jll-granvia",
            "title": "Retail — Gran Vía",
            "address": "Gran Vía 32, 28013 Madrid",
            "latitude": 40.4200, "longitude": -3.7025,
            "broker_id": "jll", "size_sqm": 130, "rent_eur_monthly": 16000,
            "property_type": "retail_high_street", "availability": "under_offer",
            "catchment_id": "mad-granvia", "street_name": "Gran Vía",
            "description": "Madrid's main commercial artery. High visibility.",
        },
    ],
}

PROPERTY_TYPE_LABELS = {
    "retail_high_street": "High Street Retail",
    "shopping_centre": "Shopping Centre Unit",
    "unit_shop": "Shop Unit",
    "pop_up": "Pop-up / Flexible",
    "mixed_use": "Mixed Use Ground Floor",
}

AVAILABILITY_LABELS = {
    "available": "Available",
    "under_offer": "Under Offer",
    "let": "Let / Occupied",
}

GOOGLE_PROPERTY_QUERIES = [
    "commercial property for rent retail",
    "shop unit to let",
    "retail space for lease",
    "high street shop rental",
    "JLL commercial property",
    "CBRE retail for lease",
]
